// Import modules
import Head from 'next/head' // Module for metadata
import styles from '../styles/Home.module.css' // styling

// Default component for the home page
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next Page</title> 
        <meta name="description" content="Generated by create next app" /> 
        <link rel="icon" href="/favicon.ico" /> 
      </Head>

      {/* Header section */}
      <header className={styles.header}>
        <h1>My Next Page</h1> 
      </header>

      {/* Main content section */}
      <main className={styles.main}>
        <section>
          <h1>h1 title</h1> 
          <p>My h1 text</p> 
        </section>
        <section>
          <h2>h2 title</h2> 
          <p>My h2 text</p> 
        </section>
      </main>

      <footer className={styles.footer}>
        <p>My Footer</p> 
      </footer>
    </div>
  )
}
